[package]
name = "lptbot"
version = "0.1.0"
authors = ["Denys Vitali <denys@denv.it>"]

[dependencies]
curl = "0.4.0"
yaml-rust = "*"
base64 = "0.6.0"
serde_json = "1.0.2"
regex = "0.2"
url = "1.5.0"
rusqlite = "0.12.0"
time = "0.1.37"
